# Generated by Django 3.2.9 on 2021-11-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20211113_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=20, upload_to='property_image/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
