# Generated by Django 3.2.9 on 2021-11-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(max_length=50, null=True, verbose_name='location'),
        ),
    ]
