# Generated by Django 3.2.9 on 2021-11-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='type',
            new_name='property_type',
        ),
    ]
