# Generated by Django 3.2.9 on 2021-11-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_rename_type_property_property_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], max_length=10),
        ),
    ]
