# Generated by Django 3.2.9 on 2021-11-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Phone_number', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'ContactDetails',
                'verbose_name_plural': 'ContactDetailss',
            },
        ),
    ]
